# Generated by Django 5.0.6 on 2024-05-17 11:33

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criate', models.DateField(auto_now_add=True, verbose_name='Date of Criation')),
                ('modificate', models.DateField(auto_now=True, verbose_name='Date of Update')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('Image', stdimage.models.StdImageField(force_min_size=False, upload_to='products', variations={'thumb': (124, 124)}, verbose_name='Image')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
